engines:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: ".eslintrc.yaml"

ratings:
   paths:
   - "index.js"

checks:
  return-statements:
    config:
      threshold: 6
