engines:
  eslint:
    enabled: true
    channel: 'eslint-9'
    config:
      config: 'eslint.config.mjs'

ratings:
  paths:
    - 'index.js'

checks:
  return-statements:
    config:
      threshold: 6
  method-complexity:
    config:
      threshold: 12